"""
Email Report Generator - Creates HTML email reports from articles.
"""

import logging
from datetime import datetime
from typing import List, Optional

from jinja2 import Environment, FileSystemLoader, select_autoescape

from .rss_fetcher import Article

logger = logging.getLogger(__name__)

# Default HTML template (used if template file not found)
DEFAULT_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ subject }}</title>
    <style>
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 600px;
            margin: 0 auto;
            padding: 20px;
            background-color: #f5f5f5;
        }
        .container {
            background-color: #ffffff;
            border-radius: 8px;
            padding: 30px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }
        h1 {
            color: #1a1a1a;
            font-size: 24px;
            margin-bottom: 10px;
            border-bottom: 3px solid #007bff;
            padding-bottom: 10px;
        }
        .date {
            color: #666;
            font-size: 14px;
            margin-bottom: 25px;
        }
        .article {
            margin-bottom: 25px;
            padding-bottom: 20px;
            border-bottom: 1px solid #eee;
        }
        .article:last-child {
            border-bottom: none;
        }
        .article-title {
            font-size: 18px;
            font-weight: 600;
            margin-bottom: 8px;
        }
        .article-title a {
            color: #007bff;
            text-decoration: none;
        }
        .article-title a:hover {
            text-decoration: underline;
        }
        .article-meta {
            font-size: 12px;
            color: #888;
            margin-bottom: 10px;
        }
        .article-meta .source {
            background-color: #e9ecef;
            padding: 2px 8px;
            border-radius: 4px;
            margin-right: 10px;
        }
        .article-meta .category {
            color: #28a745;
        }
        .article-summary {
            font-size: 14px;
            color: #555;
        }
        .footer {
            margin-top: 30px;
            padding-top: 20px;
            border-top: 1px solid #eee;
            font-size: 12px;
            color: #888;
            text-align: center;
        }
        .no-articles {
            text-align: center;
            padding: 40px;
            color: #666;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>{{ title }}</h1>
        <p class="date">{{ date }}</p>

        {% if articles %}
            {% for article in articles %}
            <div class="article">
                <div class="article-title">
                    <a href="{{ article.link }}" target="_blank">{{ article.title }}</a>
                </div>
                <div class="article-meta">
                    <span class="source">{{ article.source }}</span>
                    <span class="category">{{ article.category }}</span>
                    {% if article.published %}
                    <span class="date">{{ article.published.strftime('%b %d, %Y') }}</span>
                    {% endif %}
                </div>
                <div class="article-summary">
                    {{ article.summary }}
                </div>
            </div>
            {% endfor %}
        {% else %}
            <div class="no-articles">
                <p>No new AI news articles found today.</p>
            </div>
        {% endif %}

        <div class="footer">
            <p>Generated by Daily AI News Report</p>
            <p>{{ article_count }} articles from {{ source_count }} sources</p>
        </div>
    </div>
</body>
</html>
"""


class EmailReportGenerator:
    """Generates HTML email reports from articles."""

    def __init__(
        self,
        template_dir: Optional[str] = None,
        subject_prefix: str = "[AI News]"
    ):
        """
        Initialize the report generator.

        Args:
            template_dir: Directory containing Jinja2 templates
            subject_prefix: Prefix for email subject lines
        """
        self.subject_prefix = subject_prefix
        self.env = None

        if template_dir:
            try:
                self.env = Environment(
                    loader=FileSystemLoader(template_dir),
                    autoescape=select_autoescape(['html', 'xml'])
                )
            except Exception as e:
                logger.warning(f"Failed to load template directory: {e}")

    def generate(
        self,
        articles: List[Article],
        title: str = "Daily AI News Digest"
    ) -> dict:
        """
        Generate an HTML email report.

        Args:
            articles: List of articles to include
            title: Report title

        Returns:
            Dict with 'subject', 'html', and 'text' keys
        """
        date_str = datetime.now().strftime("%B %d, %Y")
        subject = f"{self.subject_prefix} {title} - {date_str}"

        # Get unique sources
        sources = set(a.source for a in articles)

        # Render HTML
        template_vars = {
            'title': title,
            'subject': subject,
            'date': date_str,
            'articles': articles,
            'article_count': len(articles),
            'source_count': len(sources),
        }

        html = self._render_html(template_vars)
        text = self._generate_plain_text(articles, title, date_str)

        return {
            'subject': subject,
            'html': html,
            'text': text,
        }

    def _render_html(self, template_vars: dict) -> str:
        """Render HTML using template or default."""
        if self.env:
            try:
                template = self.env.get_template('news_email.html')
                return template.render(**template_vars)
            except Exception as e:
                logger.warning(f"Template rendering failed, using default: {e}")

        # Use default template
        from jinja2 import Template
        template = Template(DEFAULT_TEMPLATE)
        return template.render(**template_vars)

    def _generate_plain_text(
        self,
        articles: List[Article],
        title: str,
        date_str: str
    ) -> str:
        """Generate plain text version of the report."""
        lines = [
            f"{title}",
            f"{date_str}",
            "=" * 50,
            "",
        ]

        if articles:
            for i, article in enumerate(articles, 1):
                lines.extend([
                    f"{i}. {article.title}",
                    f"   Source: {article.source} | Category: {article.category}",
                    f"   Link: {article.link}",
                    f"   {article.summary[:200]}...",
                    "",
                ])
        else:
            lines.append("No new AI news articles found today.")

        lines.extend([
            "=" * 50,
            f"Generated by Daily AI News Report",
            f"{len(articles)} articles",
        ])

        return "\n".join(lines)
