"""
Report Formatter for Toggl Daily Reports

Formats daily report data into HTML emails.
"""

import logging
from typing import Dict
from datetime import datetime


class ReportFormatter:
    """Formats daily report data into HTML email content."""

    def __init__(self, config: Dict):
        """
        Initialize Report Formatter.

        Args:
            config: Configuration dictionary
        """
        self.config = config
        self.logger = logging.getLogger(__name__)

    def format_daily_report(self, report_data: Dict) -> str:
        """
        Format daily report data into HTML email.

        Args:
            report_data: Report data from DailyReportGenerator

        Returns:
            HTML string for email body
        """
        self.logger.info(f"Formatting daily report for {report_data['date_formatted']}")

        html = f"""
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Toggl Daily Report</title>
</head>
<body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif; line-height: 1.6; color: #333; max-width: 800px; margin: 0 auto; padding: 20px; background-color: #f5f5f5;">

    <!-- Header -->
    <div style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 30px; border-radius: 10px 10px 0 0; text-align: center;">
        <h1 style="margin: 0; font-size: 28px; font-weight: 600;">⏱️ Toggl Daily Report</h1>
        <p style="margin: 10px 0 0 0; font-size: 16px; opacity: 0.9;">{report_data['date_formatted']}</p>
    </div>

    <!-- Main Content -->
    <div style="background: white; padding: 30px; border-radius: 0 0 10px 10px; box-shadow: 0 2px 10px rgba(0,0,0,0.1);">

        {self._format_summary_section(report_data)}

        {self._format_project_breakdown(report_data)}

        {self._format_billable_breakdown(report_data)}

        {self._format_week_summary(report_data)}

        {self._format_detailed_entries(report_data)}

    </div>

    <!-- Footer -->
    <div style="text-align: center; padding: 20px; color: #666; font-size: 12px;">
        <p style="margin: 5px 0;">Generated by Toggl Daily Report System</p>
        <p style="margin: 5px 0;">
            <a href="https://track.toggl.com/" style="color: #667eea; text-decoration: none;">View in Toggl Track</a>
        </p>
    </div>

</body>
</html>
"""
        return html

    def _format_summary_section(self, report_data: Dict) -> str:
        """Format the summary section with goal comparison."""
        goal_comp = report_data['daily_goal_comparison']
        total_hours = report_data['total_hours']

        # Determine color based on achievement
        if goal_comp['status'] == 'goal_met':
            status_color = '#10b981'  # Green
            progress_color = '#10b981'
        elif goal_comp['status'] == 'close':
            status_color = '#f59e0b'  # Amber
            progress_color = '#f59e0b'
        else:
            status_color = '#ef4444'  # Red
            progress_color = '#ef4444'

        # Calculate progress bar width (cap at 100%)
        progress_width = min(goal_comp['percentage'], 100)

        return f"""
        <!-- Summary Section -->
        <div style="margin-bottom: 30px;">
            <h2 style="color: #1f2937; font-size: 20px; margin-bottom: 15px; border-bottom: 2px solid #e5e7eb; padding-bottom: 10px;">
                📊 Daily Summary
            </h2>

            <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 15px; margin-bottom: 20px;">
                <div style="background: #f9fafb; padding: 20px; border-radius: 8px; border-left: 4px solid #667eea;">
                    <div style="font-size: 14px; color: #6b7280; margin-bottom: 5px;">Total Hours Tracked</div>
                    <div style="font-size: 32px; font-weight: 700; color: #1f2937;">{total_hours:.2f}h</div>
                    <div style="font-size: 12px; color: #9ca3af; margin-top: 5px;">{report_data['entry_count']} time entries</div>
                </div>

                <div style="background: #f9fafb; padding: 20px; border-radius: 8px; border-left: 4px solid {status_color};">
                    <div style="font-size: 14px; color: #6b7280; margin-bottom: 5px;">Daily Goal</div>
                    <div style="font-size: 32px; font-weight: 700; color: #1f2937;">{goal_comp['goal_hours']:.2f}h</div>
                    <div style="font-size: 12px; color: {status_color}; margin-top: 5px; font-weight: 600;">
                        {goal_comp['status_text']} ({goal_comp['percentage']:.1f}%)
                    </div>
                </div>
            </div>

            <!-- Progress Bar -->
            <div style="margin-top: 15px;">
                <div style="display: flex; justify-content: space-between; margin-bottom: 8px;">
                    <span style="font-size: 14px; font-weight: 600; color: #4b5563;">Goal Progress</span>
                    <span style="font-size: 14px; font-weight: 600; color: {status_color};">{goal_comp['percentage']:.1f}%</span>
                </div>
                <div style="background: #e5e7eb; height: 20px; border-radius: 10px; overflow: hidden;">
                    <div style="background: {progress_color}; height: 100%; width: {progress_width:.1f}%; border-radius: 10px; transition: width 0.3s ease;"></div>
                </div>
                <div style="font-size: 12px; color: #6b7280; margin-top: 8px; text-align: center;">
                    {abs(goal_comp['difference']):.2f}h {'ahead of' if goal_comp['difference'] >= 0 else 'behind'} goal
                </div>
            </div>
        </div>
"""

    def _format_project_breakdown(self, report_data: Dict) -> str:
        """Format the project breakdown section."""
        projects = report_data['project_breakdown']

        if not projects:
            return """
        <div style="margin-bottom: 30px;">
            <h2 style="color: #1f2937; font-size: 20px; margin-bottom: 15px; border-bottom: 2px solid #e5e7eb; padding-bottom: 10px;">
                📁 Project Breakdown
            </h2>
            <p style="color: #6b7280; font-style: italic;">No time entries tracked today.</p>
        </div>
"""

        # Define a color palette for projects
        colors = ['#667eea', '#764ba2', '#f59e0b', '#10b981', '#3b82f6', '#8b5cf6', '#ec4899']

        project_rows = ""
        for i, project in enumerate(projects):
            color = colors[i % len(colors)]
            bar_width = project['percentage']

            project_rows += f"""
                <div style="margin-bottom: 15px;">
                    <div style="display: flex; justify-content: space-between; margin-bottom: 5px;">
                        <span style="font-weight: 600; color: #374151;">{project['project']}</span>
                        <span style="color: #6b7280;">{project['hours']:.2f}h ({project['percentage']:.1f}%)</span>
                    </div>
                    <div style="background: #e5e7eb; height: 8px; border-radius: 4px; overflow: hidden;">
                        <div style="background: {color}; height: 100%; width: {bar_width:.1f}%; border-radius: 4px;"></div>
                    </div>
                </div>
"""

        return f"""
        <div style="margin-bottom: 30px;">
            <h2 style="color: #1f2937; font-size: 20px; margin-bottom: 15px; border-bottom: 2px solid #e5e7eb; padding-bottom: 10px;">
                📁 Project Breakdown
            </h2>
            {project_rows}
        </div>
"""

    def _format_billable_breakdown(self, report_data: Dict) -> str:
        """Format the billable vs non-billable breakdown."""
        billable = report_data['billable_breakdown']

        return f"""
        <div style="margin-bottom: 30px;">
            <h2 style="color: #1f2937; font-size: 20px; margin-bottom: 15px; border-bottom: 2px solid #e5e7eb; padding-bottom: 10px;">
                💰 Billable Breakdown
            </h2>

            <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 15px;">
                <div style="background: #ecfdf5; padding: 20px; border-radius: 8px; border-left: 4px solid #10b981;">
                    <div style="font-size: 14px; color: #065f46; margin-bottom: 5px; font-weight: 600;">💵 Billable</div>
                    <div style="font-size: 28px; font-weight: 700; color: #047857;">{billable['billable_hours']:.2f}h</div>
                    <div style="font-size: 12px; color: #059669; margin-top: 5px;">{billable['billable_percentage']:.1f}% of total</div>
                </div>

                <div style="background: #f3f4f6; padding: 20px; border-radius: 8px; border-left: 4px solid #6b7280;">
                    <div style="font-size: 14px; color: #374151; margin-bottom: 5px; font-weight: 600;">📝 Non-Billable</div>
                    <div style="font-size: 28px; font-weight: 700; color: #4b5563;">{billable['non_billable_hours']:.2f}h</div>
                    <div style="font-size: 12px; color: #6b7280; margin-top: 5px;">{billable['non_billable_percentage']:.1f}% of total</div>
                </div>
            </div>
        </div>
"""

    def _format_week_summary(self, report_data: Dict) -> str:
        """Format the week-to-date summary."""
        week = report_data['week_to_date_summary']

        # Determine status color
        if week['percentage'] >= 100:
            status_color = '#10b981'
            status_icon = '✓'
        elif week['percentage'] >= 80:
            status_color = '#f59e0b'
            status_icon = '~'
        else:
            status_color = '#ef4444'
            status_icon = '✗'

        return f"""
        <div style="margin-bottom: 30px;">
            <h2 style="color: #1f2937; font-size: 20px; margin-bottom: 15px; border-bottom: 2px solid #e5e7eb; padding-bottom: 10px;">
                📅 Week-to-Date Summary
            </h2>

            <div style="background: #f9fafb; padding: 20px; border-radius: 8px; border: 1px solid #e5e7eb;">
                <div style="margin-bottom: 15px;">
                    <span style="font-size: 14px; color: #6b7280;">
                        {week['week_start_formatted']} - {week['week_end_formatted']}
                    </span>
                </div>

                <div style="display: grid; grid-template-columns: repeat(3, 1fr); gap: 15px; margin-bottom: 15px;">
                    <div>
                        <div style="font-size: 12px; color: #6b7280; margin-bottom: 3px;">Total Hours</div>
                        <div style="font-size: 24px; font-weight: 700; color: #1f2937;">{week['total_hours']:.2f}h</div>
                    </div>
                    <div>
                        <div style="font-size: 12px; color: #6b7280; margin-bottom: 3px;">Avg/Day</div>
                        <div style="font-size: 24px; font-weight: 700; color: #1f2937;">{week['average_hours_per_day']:.2f}h</div>
                    </div>
                    <div>
                        <div style="font-size: 12px; color: #6b7280; margin-bottom: 3px;">Expected</div>
                        <div style="font-size: 24px; font-weight: 700; color: #1f2937;">{week['expected_hours']:.2f}h</div>
                    </div>
                </div>

                <div style="padding: 15px; background: white; border-radius: 6px; border: 1px solid #e5e7eb;">
                    <div style="display: flex; justify-content: space-between; align-items: center;">
                        <span style="font-weight: 600; color: #374151;">Week Achievement</span>
                        <span style="font-size: 18px; font-weight: 700; color: {status_color};">
                            {status_icon} {week['percentage']:.1f}%
                        </span>
                    </div>
                    <div style="font-size: 12px; color: #6b7280; margin-top: 5px;">
                        {abs(week['difference']):.2f}h {'ahead of' if week['difference'] >= 0 else 'behind'} expected ({week['days_elapsed']} days)
                    </div>
                </div>
            </div>
        </div>
"""

    def _format_detailed_entries(self, report_data: Dict) -> str:
        """Format detailed time entry list."""
        entries = report_data.get('entries', [])

        if not entries:
            return ""

        # Sort entries by start time
        sorted_entries = sorted(entries, key=lambda x: x.get('start_time', datetime.min))

        entry_rows = ""
        for entry in sorted_entries:
            project = entry.get('project_name') or '(No Project)'
            description = entry.get('description', 'No description')
            duration = entry.get('duration_display', '0h 0m')
            start_time = entry.get('start_time')
            billable_badge = '💵' if entry.get('billable') else ''

            # Format start time
            time_str = start_time.strftime('%I:%M %p') if start_time else ''

            # Tags
            tags = entry.get('tags', [])
            tags_html = ""
            if tags:
                tag_badges = " ".join([
                    f'<span style="background: #e5e7eb; color: #374151; padding: 2px 8px; border-radius: 12px; font-size: 11px; margin-left: 5px;">#{tag}</span>'
                    for tag in tags
                ])
                tags_html = tag_badges

            entry_rows += f"""
                <div style="padding: 15px; background: #f9fafb; border-radius: 6px; margin-bottom: 10px; border-left: 3px solid #667eea;">
                    <div style="display: flex; justify-content: space-between; align-items: start; margin-bottom: 5px;">
                        <div style="flex: 1;">
                            <div style="font-weight: 600; color: #1f2937; margin-bottom: 3px;">{description}</div>
                            <div style="font-size: 13px; color: #6b7280;">
                                <span style="font-weight: 500;">{project}</span>
                                {tags_html}
                            </div>
                        </div>
                        <div style="text-align: right;">
                            <div style="font-weight: 700; color: #374151; font-size: 16px;">{billable_badge} {duration}</div>
                            <div style="font-size: 12px; color: #9ca3af; margin-top: 2px;">{time_str}</div>
                        </div>
                    </div>
                </div>
"""

        return f"""
        <div style="margin-bottom: 30px;">
            <h2 style="color: #1f2937; font-size: 20px; margin-bottom: 15px; border-bottom: 2px solid #e5e7eb; padding-bottom: 10px;">
                🕐 Time Entries ({len(entries)})
            </h2>
            {entry_rows}
        </div>
"""


if __name__ == "__main__":
    # Test formatter with sample data
    sample_data = {
        'date': datetime.now(),
        'date_formatted': datetime.now().strftime('%A, %B %d, %Y'),
        'total_hours': 7.5,
        'entry_count': 8,
        'daily_goal_comparison': {
            'goal_hours': 8.0,
            'actual_hours': 7.5,
            'difference': -0.5,
            'percentage': 93.75,
            'status': 'close',
            'status_text': '~ Close to Goal'
        },
        'project_breakdown': [
            {'project': 'Client Work', 'hours': 5.0, 'percentage': 66.67},
            {'project': 'Internal Projects', 'hours': 2.0, 'percentage': 26.67},
            {'project': 'Meetings', 'hours': 0.5, 'percentage': 6.67}
        ],
        'billable_breakdown': {
            'billable_hours': 5.0,
            'non_billable_hours': 2.5,
            'total_hours': 7.5,
            'billable_percentage': 66.67,
            'non_billable_percentage': 33.33
        },
        'week_to_date_summary': {
            'week_start_formatted': 'November 17',
            'week_end_formatted': 'November 17, 2025',
            'total_hours': 7.5,
            'days_elapsed': 1,
            'average_hours_per_day': 7.5,
            'expected_hours': 8.0,
            'difference': -0.5,
            'percentage': 93.75,
            'entry_count': 8
        },
        'entries': []
    }

    formatter = ReportFormatter({})
    html = formatter.format_daily_report(sample_data)

    # Write to file for testing
    with open('test_report.html', 'w') as f:
        f.write(html)

    print("✓ Sample report generated: test_report.html")
