#!/usr/bin/env python3
"""
Quick Twilio Setup - Run this after getting your credentials from console.twilio.com
"""

import sys
from pathlib import Path

def main():
    print("=" * 60)
    print("TWILIO QUICK SETUP")
    print("=" * 60)
    print("\nPlease have your Twilio credentials ready from:")
    print("https://console.twilio.com")
    print("\n" + "-" * 60)

    # Get credentials
    print("\n1. ACCOUNT CREDENTIALS")
    print("   (Found in Account Info on Dashboard)\n")

    account_sid = input("Enter Account SID (starts with AC): ").strip()
    if not account_sid.startswith('AC') or len(account_sid) != 34:
        print("⚠️  Warning: Account SID should start with 'AC' and be 34 characters")

    auth_token = input("Enter Auth Token (32 characters): ").strip()
    if len(auth_token) != 32:
        print("⚠️  Warning: Auth Token should be 32 characters")

    print("\n2. PHONE NUMBERS")
    print("   (From Phone Numbers > Manage > Phone Numbers)\n")

    twilio_number = input("Enter your Twilio phone number (+1234567890) [optional]: ").strip()
    if twilio_number and not twilio_number.startswith('+'):
        twilio_number = '+' + twilio_number

    personal_number = input("Enter your personal number for notifications [optional]: ").strip()
    if personal_number and not personal_number.startswith('+'):
        personal_number = '+' + personal_number

    # Create .env file
    env_content = f"""# Twilio Configuration
# Generated by quick_setup.py

TWILIO_ACCOUNT_SID={account_sid}
TWILIO_AUTH_TOKEN={auth_token}
TWILIO_PHONE_NUMBER={twilio_number}
MY_PERSONAL_NUMBER={personal_number}
TWILIO_EMAIL=twilio.everglade@mymailgpt.com
"""

    env_path = Path(__file__).parent / '.env'
    env_path.write_text(env_content)

    print("\n" + "=" * 60)
    print("✅ Configuration saved to .env")
    print("=" * 60)

    # Test configuration
    print("\nTesting configuration...")
    try:
        from src.twilio_client import TwilioPersonalClient
        client = TwilioPersonalClient()
        results = client.verify_configuration()

        print("\nVERIFICATION RESULTS:")
        print("-" * 30)
        for key, value in results.items():
            status = "✅" if value else "❌"
            print(f"{status} {key.replace('_', ' ').title()}")

        if results['account_valid'] and results['phone_number_valid'] and results['personal_number_set']:
            print("\n🎉 Everything is configured! Try sending a test message:")
            print("\n   python3 src/cli.py send-self -b 'Hello from Twilio!'")

            test_now = input("\nSend a test message now? (y/n): ").lower()
            if test_now == 'y':
                try:
                    result = client.send_to_self("🎉 Twilio is working! This is a test message from your personal Twilio app.")
                    print(f"\n✅ Test message sent! Check your phone.")
                    print(f"   Message SID: {result['sid']}")
                except Exception as e:
                    print(f"\n❌ Failed to send test: {e}")
                    if "unverified" in str(e).lower():
                        print("\n⚠️  For trial accounts, verify your number at:")
                        print("   https://console.twilio.com/phone-numbers/verified")
        else:
            print("\n⚠️  Some configuration is missing:")
            if not results['phone_number_valid']:
                print("   - Buy a phone number at: https://console.twilio.com/phone-numbers/search")
            if not results['personal_number_set']:
                print("   - Add your personal number to .env file")

    except Exception as e:
        print(f"\n❌ Error testing configuration: {e}")
        print("\nPossible issues:")
        print("1. Check Account SID and Auth Token are correct")
        print("2. Make sure there are no extra spaces in credentials")
        print("3. Verify you're using the correct credentials from console.twilio.com")

if __name__ == "__main__":
    main()