#!/usr/bin/env python3
"""
Interactive Twilio Setup Script
Helps you configure and verify your Twilio account
"""

import os
import sys
from pathlib import Path
from rich.console import Console
from rich.panel import Panel
from rich.prompt import Prompt, Confirm
from rich.table import Table

# Add src to path
sys.path.append(str(Path(__file__).parent))

console = Console()

def main():
    """Interactive Twilio setup"""

    console.print(Panel.fit(
        "[bold cyan]Twilio Personal Setup Wizard[/bold cyan]\n"
        "This will help you configure your Twilio account",
        border_style="cyan"
    ))

    # Check if .env exists
    env_path = Path(__file__).parent / '.env'

    if env_path.exists():
        console.print("\n[yellow]⚠️  .env file already exists[/yellow]")
        if not Confirm.ask("Do you want to reconfigure?"):
            # Try to verify existing config
            verify_existing()
            return

    console.print("\n[bold]Step 1: Twilio Console Credentials[/bold]")
    console.print("[dim]Get these from: https://console.twilio.com[/dim]\n")

    # Collect credentials
    account_sid = Prompt.ask("Account SID (starts with AC)")
    while not account_sid.startswith('AC') or len(account_sid) != 34:
        console.print("[red]Invalid Account SID format. Should start with 'AC' and be 34 characters.[/red]")
        account_sid = Prompt.ask("Account SID (starts with AC)")

    auth_token = Prompt.ask("Auth Token", password=True)
    while len(auth_token) != 32:
        console.print("[red]Invalid Auth Token format. Should be 32 characters.[/red]")
        auth_token = Prompt.ask("Auth Token", password=True)

    console.print("\n[bold]Step 2: Phone Numbers[/bold]")
    console.print("[dim]Leave blank if you haven't purchased a number yet[/dim]\n")

    twilio_number = Prompt.ask(
        "Your Twilio Phone Number (E.164 format: +1234567890)",
        default=""
    )

    if twilio_number and not twilio_number.startswith('+'):
        twilio_number = '+' + twilio_number

    personal_number = Prompt.ask(
        "Your Personal Number (for receiving notifications)",
        default=""
    )

    if personal_number and not personal_number.startswith('+'):
        personal_number = '+' + personal_number

    # Write .env file
    env_content = f"""# Twilio Configuration
# Generated by setup script

TWILIO_ACCOUNT_SID={account_sid}
TWILIO_AUTH_TOKEN={auth_token}
TWILIO_PHONE_NUMBER={twilio_number}
MY_PERSONAL_NUMBER={personal_number}
TWILIO_EMAIL=twilio.everglade@mymailgpt.com
"""

    env_path.write_text(env_content)
    console.print(f"\n[green]✓ Configuration saved to .env[/green]")

    # Verify configuration
    if Confirm.ask("\nWould you like to verify your configuration?"):
        verify_config(account_sid, twilio_number, personal_number)

def verify_existing():
    """Verify existing configuration"""
    try:
        from src.twilio_client import TwilioPersonalClient

        console.print("\n[cyan]Verifying existing configuration...[/cyan]")

        client = TwilioPersonalClient()
        results = client.verify_configuration()

        table = Table(title="Configuration Status")
        table.add_column("Check", style="cyan")
        table.add_column("Status", style="green")

        for check, status in results.items():
            status_icon = "✅" if status else "❌"
            table.add_row(check.replace('_', ' ').title(), status_icon)

        console.print(table)

        if all(results.values()):
            console.print("\n[green]✅ All checks passed! Your Twilio setup is working.[/green]")
        else:
            console.print("\n[yellow]⚠️  Some checks failed. Please review your configuration.[/yellow]")

    except Exception as e:
        console.print(f"\n[red]❌ Error: {e}[/red]")
        console.print("[yellow]Please check your .env file and credentials[/yellow]")

def verify_config(account_sid, twilio_number, personal_number):
    """Verify the configuration"""
    try:
        from src.twilio_client import TwilioPersonalClient

        console.print("\n[cyan]Testing your Twilio configuration...[/cyan]")

        client = TwilioPersonalClient()
        results = client.verify_configuration()

        # Display results
        table = Table(title="Verification Results")
        table.add_column("Component", style="cyan")
        table.add_column("Status", style="green")
        table.add_column("Details")

        table.add_row(
            "Account",
            "✅" if results['account_valid'] else "❌",
            f"SID: {account_sid[:8]}..."
        )

        table.add_row(
            "Twilio Number",
            "✅" if results['phone_number_valid'] else "⚠️",
            twilio_number or "Not configured"
        )

        table.add_row(
            "Personal Number",
            "✅" if results['personal_number_set'] else "⚠️",
            personal_number or "Not configured"
        )

        table.add_row(
            "SMS Capability",
            "✅" if results['can_send_sms'] else "⚠️",
            "Ready" if results['can_send_sms'] else "Number needed"
        )

        console.print(table)

        # Provide next steps
        console.print("\n[bold]Next Steps:[/bold]")

        if not twilio_number:
            console.print("1. [yellow]Buy a phone number at: https://console.twilio.com/phone-numbers/search[/yellow]")
            console.print("   Then run: python setup.py")

        if not personal_number:
            console.print("2. [yellow]Add your personal number to receive notifications[/yellow]")

        if results['account_valid'] and twilio_number and personal_number:
            console.print("✅ You're all set! Try sending a test message:")
            console.print("   [cyan]python src/cli.py send-self -b 'Hello from Twilio!'[/cyan]")

            if Confirm.ask("\nWould you like to send a test message now?"):
                try:
                    result = client.send_to_self("🎉 Twilio is configured successfully! This is a test message.")
                    console.print(f"\n[green]✅ Test message sent! Check your phone.[/green]")
                    console.print(f"[dim]Message SID: {result['sid']}[/dim]")
                except Exception as e:
                    console.print(f"\n[red]❌ Failed to send test: {e}[/red]")
                    if "unverified" in str(e).lower():
                        console.print("[yellow]For trial accounts, verify your number at:[/yellow]")
                        console.print("https://console.twilio.com/phone-numbers/verified")

    except ImportError:
        console.print("\n[red]❌ Error: Could not import Twilio client.[/red]")
        console.print("Make sure dependencies are installed: pip3 install -r requirements.txt")
    except Exception as e:
        console.print(f"\n[red]❌ Error during verification: {e}[/red]")

        # Common troubleshooting
        if "authenticate" in str(e).lower():
            console.print("\n[yellow]Authentication failed. Please check:[/yellow]")
            console.print("1. Account SID is correct (34 characters starting with AC)")
            console.print("2. Auth Token is correct (32 characters)")
            console.print("3. No extra spaces in credentials")
        elif "phone" in str(e).lower():
            console.print("\n[yellow]Phone number issue. Please check:[/yellow]")
            console.print("1. Number is in E.164 format (+1234567890)")
            console.print("2. Number is purchased in your Twilio account")

if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        console.print("\n[yellow]Setup cancelled.[/yellow]")
    except Exception as e:
        console.print(f"\n[red]Unexpected error: {e}[/red]")
        sys.exit(1)